# Generated by Django 3.0.8 on 2020-07-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Tweet',
        ),
    ]
