# Generated by Django 3.0.8 on 2020-07-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0003_auto_20200724_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='begeniSayisi',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='yorumSayisi',
        ),
    ]
