# Generated by Django 3.0.8 on 2020-07-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0003_tweet_begenisayisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='yorumSayisi',
            field=models.IntegerField(default=0),
        ),
    ]
