# Generated by Django 3.0.8 on 2020-07-24 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0005_begeni_yorum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Begeni',
        ),
        migrations.DeleteModel(
            name='Yorum',
        ),
    ]
