# Generated by Django 3.0.8 on 2020-07-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0006_auto_20200728_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='owner',
        ),
    ]
