# Generated by Django 3.0.8 on 2020-07-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0007_remove_tweet_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='date',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
