# Generated by Django 3.0.8 on 2020-07-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0008_auto_20200728_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=280),
        ),
    ]
