# Generated by Django 3.0.8 on 2020-07-29 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tweet', '0011_auto_20200728_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='begeniSayisi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tweet',
            name='yorumSayisi',
            field=models.IntegerField(default=0),
        ),
    ]
