# Generated by Django 3.0.8 on 2020-08-07 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0012_auto_20200729_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='owner',
        ),
    ]
