# Generated by Django 3.0.8 on 2020-08-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0014_auto_20200813_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='begeniSayisi',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='yorumSayisi',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
