# Generated by Django 3.0.8 on 2020-08-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0017_auto_20200816_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
