# Generated by Django 3.0.8 on 2020-08-15 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0018_comment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('date',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
