# Generated by Django 3.0.8 on 2020-08-17 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0032_auto_20200817_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='begeniSayisi',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='yorumSayisi',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='begeniSayisi',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='yorumSayisi',
        ),
        migrations.AddField(
            model_name='tweet',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='Tweet.Comment'),
        ),
    ]
