# Generated by Django 3.0.8 on 2020-08-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0033_auto_20200817_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='comment',
        ),
    ]
