# Generated by Django 3.0.8 on 2020-08-17 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0034_remove_tweet_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='begeniSayisi',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Tweet.Tweet'),
        ),
        migrations.AddField(
            model_name='comment',
            name='yorumSayisi',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='begeniSayisi',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='yorumSayisi',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
