# Generated by Django 3.0.8 on 2020-08-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0036_auto_20200817_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tweet',
            field=models.IntegerField(null=True),
        ),
    ]
